### ISSUE TITLE
Mixed effects model could not be fit"

### ISSUE THREAD

**Issue by AbigailLoe** [bcjaeger/bimm#12]
I am attempting to read through your code and possibly use BiMM for some of my own research. However, I have been unable to run the examples shown in your ReadMe file. I received the following errors:

Beginning iteration 1...mixed effects model could not be fit; ending on iteration 1
Warning messages:
1: In get(optimizer) : restarting interrupted promise evaluation
2: In get(optimizer) : internal error -3 in R_decompress1

I also attempted to run this on an example dataset of my own and I received the same warning/error messages from bimm_fit.

**Comment by bcjaeger** [comment]
@AbigailLoe, did this issue work itself out? I have been on an extended break from `bimm` but I will be happy to review this issue when I return if it's still causing errors.

**Comment by AbigailLoe** [comment]
Yes, for some reason it fixed itself. I did nothing differently, tried again this morning and somehow it worked ¯\ _(ツ)_/¯
