### ISSUE TITLE
model_mer predictions

### ISSUE THREAD

**Issue by speiser10** [bcjaeger/bimm#2]
we need a function that takes a test dataset of new observations for subjects included in training data that calculates the predicted probability from the ML model `._x_.` and uses this in the model_mer to predict the outcome.

**Comment by bcjaeger** [comment]
I added a predict function. Let me know what you think! I think the main thing to add may be switching the type of predictions returned, e.g., linear predictors or probabilities. Also, the function is not documented yet. In case it is confusing, just shoot me an e-mail and I can explain.
