### ISSUE TITLE
create summary statement

### ISSUE THREAD

**Issue by speiser10** [bcjaeger/bimm#6]
using summary to write more expressive prints:
output from RF
output from GLMM

**Comment by bcjaeger** [comment]
Done! I will close this issue but if you'd like to see changes to the summary function then we can open a new one.

**Comment by speiser10** [comment]
Hey Byron--someone using the package emailed and asked about the summary table having auc_test and bri_test with NA's. When I look at the summary(model) and print(model) this is the case. In the model statement, there isn't anything for test=dataset_testname. So maybe can you just delete the auc_test and bri_test columns in the summary and print functions? If you think this is the best way to handle it. (No rush at all on doing this, it's really not a big deal just thought I'd ask since someone pointed it out to me). Thanks!
